name: Deploy Zadania·AP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Wyślij pliki (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          server:      ${{ secrets.FTP_SERVER }}
          username:    ${{ secrets.FTP_USERNAME }}
          password:    ${{ secrets.FTP_PASSWORD }}
          port:        2222
          local_path:  './*'
          remote_path: 'sites/poponczyk.com/zadania/public_html'
          sftp_only:   'true'
          delete_remote_files: 'false'
